packages:
  - packages/*
  - apps/*
catalogs:
  discordjs:
    discord.js: ^14.25.1
  build:
    typescript: ^5.9.3
    tsdown: ^0.21.0-beta.2
  workflow:
    workflow: ^4.1.0-beta.60
    '@workflow/builders': ^4.0.1-beta.53
    '@workflow/rollup': '^4.0.0-beta.19'
